/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_codegen_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f21 CASADI_PREFIX(f21)
#define casadi_f22 CASADI_PREFIX(f22)
#define casadi_f23 CASADI_PREFIX(f23)
#define casadi_f24 CASADI_PREFIX(f24)
#define casadi_f25 CASADI_PREFIX(f25)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[36] = {32, 1, 0, 32, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const casadi_int casadi_s2[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[27] = {5, 4, 0, 5, 10, 15, 20, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[4] = {0, 1, 0, 0};
static const casadi_int casadi_s7[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s8[3] = {5, 0, 0};
static const casadi_int casadi_s9[3] = {3, 0, 0};

/* BAbt:(i0[2],i1[2],i2[2],i3[32],i4[2])->(o0[5x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=5.0000000000000003e-02;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  a2=1.;
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a1;
  a3=arg[2]? arg[2][0] : 0;
  a4=8.3333333333333332e-03;
  a5=arg[1]? arg[1][0] : 0;
  a6=2.;
  a7=(a6*a5);
  a7=(a5+a7);
  a8=(a6*a5);
  a7=(a7+a8);
  a7=(a7+a5);
  a7=(a4*a7);
  a3=(a3+a7);
  a7=arg[0]? arg[0][0] : 0;
  a3=(a3-a7);
  if (res[0]!=0) res[0][4]=a3;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a2;
  a2=arg[2]? arg[2][1] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a0=(a6*a1);
  a0=(a1+a0);
  a6=(a6*a1);
  a0=(a0+a6);
  a0=(a0+a1);
  a4=(a4*a0);
  a2=(a2+a4);
  a4=arg[0]? arg[0][1] : 0;
  a2=(a2-a4);
  if (res[0]!=0) res[0][9]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int BAbt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BAbt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BAbt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BAbt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BAbt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BAbt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BAbt_incref(void) {
}

CASADI_SYMBOL_EXPORT void BAbt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BAbt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int BAbt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BAbt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BAbt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BAbt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BAbt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BAbt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BAbt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* bk:(i0[2],i1[2],i2[2],i3[32],i4[2])->(o0[2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[2]? arg[2][0] : 0;
  a1=8.3333333333333332e-03;
  a2=arg[1]? arg[1][0] : 0;
  a3=2.;
  a4=(a3*a2);
  a4=(a2+a4);
  a5=(a3*a2);
  a4=(a4+a5);
  a4=(a4+a2);
  a4=(a1*a4);
  a0=(a0+a4);
  a4=arg[0]? arg[0][0] : 0;
  a0=(a0-a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a2=(a3*a4);
  a2=(a4+a2);
  a3=(a3*a4);
  a2=(a2+a3);
  a2=(a2+a4);
  a1=(a1*a2);
  a0=(a0+a1);
  a1=arg[0]? arg[0][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bk_incref(void) {
}

CASADI_SYMBOL_EXPORT void bk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bk_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bk_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bk_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtI:(i0,i1[2],i2[2],i3[2],i4[2],i5[2],i6[32],i7[2])->(o0[5x4]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a0*a2);
  a3=8.3333333333333332e-03;
  a4=arg[3]? arg[3][0] : 0;
  a5=(a3*a4);
  a6=(a0*a5);
  a6=(a5+a6);
  a6=(a6+a5);
  a5=(a0*a5);
  a6=(a6+a5);
  a2=(a2+a6);
  a6=arg[5]? arg[5][0] : 0;
  a2=(a2+a6);
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a2=arg[1]? arg[1][1] : 0;
  a2=(a0*a2);
  a6=arg[3]? arg[3][1] : 0;
  a3=(a3*a6);
  a5=(a0*a3);
  a5=(a3+a5);
  a5=(a5+a3);
  a3=(a0*a3);
  a5=(a5+a3);
  a2=(a2+a5);
  a5=arg[5]? arg[5][1] : 0;
  a2=(a2+a5);
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  a2=10.;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a1;
  a5=arg[4]? arg[4][0] : 0;
  a3=arg[6]? arg[6][28] : 0;
  a7=arg[2]? arg[2][0] : 0;
  a3=(a3-a7);
  a8=arg[6]? arg[6][12] : 0;
  a3=(a3+a8);
  a8=arg[6]? arg[6][30] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][14] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][26] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][10] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][24] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][8] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][22] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][6] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][20] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][4] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][18] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][2] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][16] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][0] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=2.3199999999999998e+00;
  a8=(a8-a7);
  a8=(a0*a8);
  a3=(a3+a8);
  a5=(a5-a3);
  a5=(a5+a4);
  if (res[0]!=0) res[0][14]=a5;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a2;
  a2=arg[4]? arg[4][1] : 0;
  a1=arg[6]? arg[6][29] : 0;
  a5=arg[2]? arg[2][1] : 0;
  a1=(a1-a5);
  a4=arg[6]? arg[6][13] : 0;
  a1=(a1+a4);
  a4=arg[6]? arg[6][31] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][15] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][27] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][11] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][25] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][9] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][23] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][7] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][21] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][5] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][19] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][3] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][17] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][1] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=1.8200000000000001e+00;
  a4=(a4-a5);
  a0=(a0*a4);
  a1=(a1+a0);
  a2=(a2-a1);
  a2=(a2+a6);
  if (res[0]!=0) res[0][19]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtI_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtI_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtI_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtI_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtI_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtIGN:(i0,i1[2],i2[2],i3[2],i4[2],i5[2],i6[32],i7[2])->(o0[5x4]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a0*a2);
  a3=8.3333333333333332e-03;
  a4=arg[3]? arg[3][0] : 0;
  a5=(a3*a4);
  a6=(a0*a5);
  a6=(a5+a6);
  a6=(a6+a5);
  a5=(a0*a5);
  a6=(a6+a5);
  a2=(a2+a6);
  a6=arg[5]? arg[5][0] : 0;
  a2=(a2+a6);
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a2=arg[1]? arg[1][1] : 0;
  a2=(a0*a2);
  a6=arg[3]? arg[3][1] : 0;
  a3=(a3*a6);
  a5=(a0*a3);
  a5=(a3+a5);
  a5=(a5+a3);
  a3=(a0*a3);
  a5=(a5+a3);
  a2=(a2+a5);
  a5=arg[5]? arg[5][1] : 0;
  a2=(a2+a5);
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  a2=10.;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a1;
  a5=arg[4]? arg[4][0] : 0;
  a3=arg[6]? arg[6][28] : 0;
  a7=arg[2]? arg[2][0] : 0;
  a3=(a3-a7);
  a8=arg[6]? arg[6][12] : 0;
  a3=(a3+a8);
  a8=arg[6]? arg[6][30] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][14] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][26] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][10] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][24] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][8] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][22] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][6] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][20] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][4] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][18] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][2] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=arg[6]? arg[6][16] : 0;
  a8=(a8-a7);
  a9=arg[6]? arg[6][0] : 0;
  a8=(a8+a9);
  a3=(a3+a8);
  a8=2.3199999999999998e+00;
  a8=(a8-a7);
  a8=(a0*a8);
  a3=(a3+a8);
  a5=(a5-a3);
  a5=(a5+a4);
  if (res[0]!=0) res[0][14]=a5;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a2;
  a2=arg[4]? arg[4][1] : 0;
  a1=arg[6]? arg[6][29] : 0;
  a5=arg[2]? arg[2][1] : 0;
  a1=(a1-a5);
  a4=arg[6]? arg[6][13] : 0;
  a1=(a1+a4);
  a4=arg[6]? arg[6][31] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][15] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][27] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][11] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][25] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][9] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][23] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][7] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][21] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][5] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][19] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][3] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=arg[6]? arg[6][17] : 0;
  a4=(a4-a5);
  a3=arg[6]? arg[6][1] : 0;
  a4=(a4+a3);
  a1=(a1+a4);
  a4=1.8200000000000001e+00;
  a4=(a4-a5);
  a0=(a0*a4);
  a1=(a1+a0);
  a2=(a2-a1);
  a2=(a2+a6);
  if (res[0]!=0) res[0][19]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtIGN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtIGN_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtIGN_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtIGN_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtIGN_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtIGN_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtIGN_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtIGN_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtIGN_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtIGN_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtIGN_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtIGN_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtIGN_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtIGN_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtIGN_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtIGN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqI:(i0,i1[2],i2[2],i3[32],i4[2])->(o0[4]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=2.;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[3]? arg[3][28] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a1=(a1-a2);
  a3=arg[3]? arg[3][12] : 0;
  a1=(a1+a3);
  a3=arg[3]? arg[3][30] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][14] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][26] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][10] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][24] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][8] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][22] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][6] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][20] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][4] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][18] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][16] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=2.3199999999999998e+00;
  a3=(a3-a2);
  a3=(a0*a3);
  a1=(a1+a3);
  a1=(-a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[3]? arg[3][29] : 0;
  a3=arg[2]? arg[2][1] : 0;
  a1=(a1-a3);
  a2=arg[3]? arg[3][13] : 0;
  a1=(a1+a2);
  a2=arg[3]? arg[3][31] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][15] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][27] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][11] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][25] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][9] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][23] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][7] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][21] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][5] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][19] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][3] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][17] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][1] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=1.8200000000000001e+00;
  a2=(a2-a3);
  a0=(a0*a2);
  a1=(a1+a0);
  a1=(-a1);
  if (res[0]!=0) res[0][3]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqI_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqI_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rqI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqI_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqI_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqI_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqt:(i0,i1[2],i2[2],i3[2],i4[0],i5[2],i6[32],i7[2])->(o0[5x4]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a0*a2);
  a3=8.3333333333333332e-03;
  a4=arg[3]? arg[3][0] : 0;
  a5=(a3*a4);
  a6=(a0*a5);
  a6=(a5+a6);
  a6=(a6+a5);
  a5=(a0*a5);
  a6=(a6+a5);
  a2=(a2+a6);
  a6=arg[5]? arg[5][0] : 0;
  a2=(a2+a6);
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a2=arg[1]? arg[1][1] : 0;
  a2=(a0*a2);
  a6=arg[3]? arg[3][1] : 0;
  a3=(a3*a6);
  a5=(a0*a3);
  a5=(a3+a5);
  a5=(a5+a3);
  a3=(a0*a3);
  a5=(a5+a3);
  a2=(a2+a5);
  a5=arg[5]? arg[5][1] : 0;
  a2=(a2+a5);
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  a2=10.;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a1;
  a5=arg[6]? arg[6][28] : 0;
  a3=arg[2]? arg[2][0] : 0;
  a5=(a5-a3);
  a7=arg[6]? arg[6][12] : 0;
  a5=(a5+a7);
  a7=arg[6]? arg[6][30] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][14] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][26] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][10] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][24] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][8] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][22] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][6] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][20] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][4] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][18] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][2] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][16] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][0] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=2.3199999999999998e+00;
  a7=(a7-a3);
  a7=(a0*a7);
  a5=(a5+a7);
  a4=(a4-a5);
  if (res[0]!=0) res[0][14]=a4;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a2;
  a2=arg[6]? arg[6][29] : 0;
  a1=arg[2]? arg[2][1] : 0;
  a2=(a2-a1);
  a4=arg[6]? arg[6][13] : 0;
  a2=(a2+a4);
  a4=arg[6]? arg[6][31] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][15] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][27] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][11] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][25] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][9] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][23] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][7] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][21] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][5] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][19] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][3] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][17] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][1] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=1.8200000000000001e+00;
  a4=(a4-a1);
  a0=(a0*a4);
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][19]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqt_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqt_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtGN:(i0,i1[2],i2[2],i3[2],i4[0],i5[2],i6[32],i7[2])->(o0[5x4]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a2=(a0*a2);
  a3=8.3333333333333332e-03;
  a4=arg[3]? arg[3][0] : 0;
  a5=(a3*a4);
  a6=(a0*a5);
  a6=(a5+a6);
  a6=(a6+a5);
  a5=(a0*a5);
  a6=(a6+a5);
  a2=(a2+a6);
  a6=arg[5]? arg[5][0] : 0;
  a2=(a2+a6);
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a2=arg[1]? arg[1][1] : 0;
  a2=(a0*a2);
  a6=arg[3]? arg[3][1] : 0;
  a3=(a3*a6);
  a5=(a0*a3);
  a5=(a3+a5);
  a5=(a5+a3);
  a3=(a0*a3);
  a5=(a5+a3);
  a2=(a2+a5);
  a5=arg[5]? arg[5][1] : 0;
  a2=(a2+a5);
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  a2=10.;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a1;
  a5=arg[6]? arg[6][28] : 0;
  a3=arg[2]? arg[2][0] : 0;
  a5=(a5-a3);
  a7=arg[6]? arg[6][12] : 0;
  a5=(a5+a7);
  a7=arg[6]? arg[6][30] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][14] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][26] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][10] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][24] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][8] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][22] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][6] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][20] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][4] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][18] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][2] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=arg[6]? arg[6][16] : 0;
  a7=(a7-a3);
  a8=arg[6]? arg[6][0] : 0;
  a7=(a7+a8);
  a5=(a5+a7);
  a7=2.3199999999999998e+00;
  a7=(a7-a3);
  a7=(a0*a7);
  a5=(a5+a7);
  a4=(a4-a5);
  if (res[0]!=0) res[0][14]=a4;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a2;
  a2=arg[6]? arg[6][29] : 0;
  a1=arg[2]? arg[2][1] : 0;
  a2=(a2-a1);
  a4=arg[6]? arg[6][13] : 0;
  a2=(a2+a4);
  a4=arg[6]? arg[6][31] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][15] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][27] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][11] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][25] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][9] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][23] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][7] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][21] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][5] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][19] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][3] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][17] : 0;
  a4=(a4-a1);
  a5=arg[6]? arg[6][1] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=1.8200000000000001e+00;
  a4=(a4-a1);
  a0=(a0*a4);
  a2=(a2+a0);
  a6=(a6-a2);
  if (res[0]!=0) res[0][19]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtGN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtGN_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtGN_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtGN_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtGN_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtGN_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtGN_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtGN_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtGN_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtGN_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtGN_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtGN_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtGN_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtGN_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtGN_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtGN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqk:(i0,i1[2],i2[2],i3[32],i4[2])->(o0[4]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=2.;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[3]? arg[3][28] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a1=(a1-a2);
  a3=arg[3]? arg[3][12] : 0;
  a1=(a1+a3);
  a3=arg[3]? arg[3][30] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][14] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][26] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][10] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][24] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][8] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][22] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][6] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][20] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][4] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][18] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=arg[3]? arg[3][16] : 0;
  a3=(a3-a2);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3+a4);
  a1=(a1+a3);
  a3=2.3199999999999998e+00;
  a3=(a3-a2);
  a3=(a0*a3);
  a1=(a1+a3);
  a1=(-a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[3]? arg[3][29] : 0;
  a3=arg[2]? arg[2][1] : 0;
  a1=(a1-a3);
  a2=arg[3]? arg[3][13] : 0;
  a1=(a1+a2);
  a2=arg[3]? arg[3][31] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][15] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][27] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][11] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][25] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][9] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][23] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][7] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][21] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][5] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][19] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][3] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=arg[3]? arg[3][17] : 0;
  a2=(a2-a3);
  a4=arg[3]? arg[3][1] : 0;
  a2=(a2+a4);
  a1=(a1+a2);
  a2=1.8200000000000001e+00;
  a2=(a2-a3);
  a0=(a0*a2);
  a1=(a1+a0);
  a1=(-a1);
  if (res[0]!=0) res[0][3]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqk_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rqk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqk_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqk_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqk_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* LI:(i0,i1[2],i2[2],i3[32],i4[2])->(o0) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=2.3199999999999998e+00;
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a2=1.8200000000000001e+00;
  a3=arg[2]? arg[2][1] : 0;
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a0=(a0+a2);
  a2=arg[1]? arg[1][0] : 0;
  a2=casadi_sq(a2);
  a4=arg[1]? arg[1][1] : 0;
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][0] : 0;
  a4=arg[3]? arg[3][16] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a5=arg[3]? arg[3][1] : 0;
  a6=arg[3]? arg[3][17] : 0;
  a6=(a6-a3);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=5.0000000000000000e-01;
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][2] : 0;
  a4=arg[3]? arg[3][18] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][3] : 0;
  a7=arg[3]? arg[3][19] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][4] : 0;
  a4=arg[3]? arg[3][20] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][5] : 0;
  a6=arg[3]? arg[3][21] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][6] : 0;
  a4=arg[3]? arg[3][22] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][7] : 0;
  a7=arg[3]? arg[3][23] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][8] : 0;
  a4=arg[3]? arg[3][24] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][9] : 0;
  a6=arg[3]? arg[3][25] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][10] : 0;
  a4=arg[3]? arg[3][26] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][11] : 0;
  a7=arg[3]? arg[3][27] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][12] : 0;
  a4=arg[3]? arg[3][28] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][13] : 0;
  a6=arg[3]? arg[3][29] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][14] : 0;
  a4=arg[3]? arg[3][30] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a1=arg[3]? arg[3][15] : 0;
  a6=arg[3]? arg[3][31] : 0;
  a6=(a6-a3);
  a1=(a1*a6);
  a2=(a2+a1);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a5=(a5*a4);
  a2=(a2+a5);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int LI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int LI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int LI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int LI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void LI_incref(void) {
}

CASADI_SYMBOL_EXPORT void LI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int LI_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int LI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real LI_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LI_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LI_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int LI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Lk:(i0,i1[2],i2[2],i3[32],i4[2])->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=2.3199999999999998e+00;
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a2=1.8200000000000001e+00;
  a3=arg[2]? arg[2][1] : 0;
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a0=(a0+a2);
  a2=arg[1]? arg[1][0] : 0;
  a2=casadi_sq(a2);
  a4=arg[1]? arg[1][1] : 0;
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][0] : 0;
  a4=arg[3]? arg[3][16] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a5=arg[3]? arg[3][1] : 0;
  a6=arg[3]? arg[3][17] : 0;
  a6=(a6-a3);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=5.0000000000000000e-01;
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][2] : 0;
  a4=arg[3]? arg[3][18] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][3] : 0;
  a7=arg[3]? arg[3][19] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][4] : 0;
  a4=arg[3]? arg[3][20] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][5] : 0;
  a6=arg[3]? arg[3][21] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][6] : 0;
  a4=arg[3]? arg[3][22] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][7] : 0;
  a7=arg[3]? arg[3][23] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][8] : 0;
  a4=arg[3]? arg[3][24] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][9] : 0;
  a6=arg[3]? arg[3][25] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][10] : 0;
  a4=arg[3]? arg[3][26] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][11] : 0;
  a7=arg[3]? arg[3][27] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][12] : 0;
  a4=arg[3]? arg[3][28] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][13] : 0;
  a6=arg[3]? arg[3][29] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][14] : 0;
  a4=arg[3]? arg[3][30] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a1=arg[3]? arg[3][15] : 0;
  a6=arg[3]? arg[3][31] : 0;
  a6=(a6-a3);
  a1=(a1*a6);
  a2=(a2+a1);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a5=(a5*a4);
  a2=(a2+a5);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Lk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Lk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Lk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Lk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Lk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Lk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Lk_incref(void) {
}

CASADI_SYMBOL_EXPORT void Lk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Lk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Lk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Lk_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Lk_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Lk_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Lk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Lk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Lk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtF:(i0,i1[2],i2[2],i3[2],i4[0],i5[0],i6[32],i7[2])->(o0[3x2]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=10.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[6]? arg[6][28] : 0;
  a3=arg[2]? arg[2][0] : 0;
  a2=(a2-a3);
  a4=arg[6]? arg[6][12] : 0;
  a2=(a2+a4);
  a4=arg[6]? arg[6][30] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][14] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][26] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][10] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][24] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][8] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][22] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][6] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][20] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][4] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][18] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][2] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][16] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][0] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=2.;
  a5=2.3199999999999998e+00;
  a5=(a5-a3);
  a5=(a4*a5);
  a2=(a2+a5);
  a2=(-a2);
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[6]? arg[6][29] : 0;
  a1=arg[2]? arg[2][1] : 0;
  a0=(a0-a1);
  a2=arg[6]? arg[6][13] : 0;
  a0=(a0+a2);
  a2=arg[6]? arg[6][31] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][15] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][27] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][11] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][25] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][9] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][23] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][7] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][21] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][5] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][19] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][3] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][17] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][1] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=1.8200000000000001e+00;
  a2=(a2-a1);
  a4=(a4*a2);
  a0=(a0+a4);
  a0=(-a0);
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtF_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtF_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s6;
    case 5: return casadi_s6;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtFGN:(i0,i1[2],i2[2],i3[2],i4[0],i5[0],i6[32],i7[2])->(o0[3x2]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=10.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[6]? arg[6][28] : 0;
  a3=arg[2]? arg[2][0] : 0;
  a2=(a2-a3);
  a4=arg[6]? arg[6][12] : 0;
  a2=(a2+a4);
  a4=arg[6]? arg[6][30] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][14] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][26] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][10] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][24] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][8] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][22] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][6] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][20] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][4] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][18] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][2] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=arg[6]? arg[6][16] : 0;
  a4=(a4-a3);
  a5=arg[6]? arg[6][0] : 0;
  a4=(a4+a5);
  a2=(a2+a4);
  a4=2.;
  a5=2.3199999999999998e+00;
  a5=(a5-a3);
  a5=(a4*a5);
  a2=(a2+a5);
  a2=(-a2);
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[6]? arg[6][29] : 0;
  a1=arg[2]? arg[2][1] : 0;
  a0=(a0-a1);
  a2=arg[6]? arg[6][13] : 0;
  a0=(a0+a2);
  a2=arg[6]? arg[6][31] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][15] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][27] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][11] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][25] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][9] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][23] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][7] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][21] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][5] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][19] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][3] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=arg[6]? arg[6][17] : 0;
  a2=(a2-a1);
  a5=arg[6]? arg[6][1] : 0;
  a2=(a2+a5);
  a0=(a0+a2);
  a2=1.8200000000000001e+00;
  a2=(a2-a1);
  a4=(a4*a2);
  a0=(a0+a4);
  a0=(-a0);
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtFGN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtFGN_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtFGN_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtFGN_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtFGN_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtFGN_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtFGN_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtFGN_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtFGN_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtFGN_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtFGN_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtFGN_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtFGN_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtFGN_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s6;
    case 5: return casadi_s6;
    case 6: return casadi_s1;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtFGN_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtFGN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqF:(i0,i1[2],i2[2],i3[32],i4[2])->(o0[2]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[3]? arg[3][28] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0-a1);
  a2=arg[3]? arg[3][12] : 0;
  a0=(a0+a2);
  a2=arg[3]? arg[3][30] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][14] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][26] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][10] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][24] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][8] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][22] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][6] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][20] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][4] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][18] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][2] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][16] : 0;
  a2=(a2-a1);
  a3=arg[3]? arg[3][0] : 0;
  a2=(a2+a3);
  a0=(a0+a2);
  a2=2.;
  a3=2.3199999999999998e+00;
  a3=(a3-a1);
  a3=(a2*a3);
  a0=(a0+a3);
  a0=(-a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][29] : 0;
  a3=arg[2]? arg[2][1] : 0;
  a0=(a0-a3);
  a1=arg[3]? arg[3][13] : 0;
  a0=(a0+a1);
  a1=arg[3]? arg[3][31] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][15] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][27] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][11] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][25] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][9] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][23] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][7] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][21] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][5] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][19] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][3] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][17] : 0;
  a1=(a1-a3);
  a4=arg[3]? arg[3][1] : 0;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=1.8200000000000001e+00;
  a1=(a1-a3);
  a2=(a2*a1);
  a0=(a0+a2);
  a0=(-a0);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqF_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rqF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* LF:(i0,i1[2],i2[2],i3[32],i4[2])->(o0) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=2.3199999999999998e+00;
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a2=1.8200000000000001e+00;
  a3=arg[2]? arg[2][1] : 0;
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a0=(a0+a2);
  a2=arg[1]? arg[1][0] : 0;
  a2=casadi_sq(a2);
  a4=arg[1]? arg[1][1] : 0;
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][0] : 0;
  a4=arg[3]? arg[3][16] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a5=arg[3]? arg[3][1] : 0;
  a6=arg[3]? arg[3][17] : 0;
  a6=(a6-a3);
  a5=(a5*a6);
  a2=(a2+a5);
  a5=5.0000000000000000e-01;
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][2] : 0;
  a4=arg[3]? arg[3][18] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][3] : 0;
  a7=arg[3]? arg[3][19] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][4] : 0;
  a4=arg[3]? arg[3][20] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][5] : 0;
  a6=arg[3]? arg[3][21] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][6] : 0;
  a4=arg[3]? arg[3][22] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][7] : 0;
  a7=arg[3]? arg[3][23] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][8] : 0;
  a4=arg[3]? arg[3][24] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][9] : 0;
  a6=arg[3]? arg[3][25] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][10] : 0;
  a4=arg[3]? arg[3][26] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a6=arg[3]? arg[3][11] : 0;
  a7=arg[3]? arg[3][27] : 0;
  a7=(a7-a3);
  a6=(a6*a7);
  a2=(a2+a6);
  a4=casadi_sq(a4);
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][12] : 0;
  a4=arg[3]? arg[3][28] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a7=arg[3]? arg[3][13] : 0;
  a6=arg[3]? arg[3][29] : 0;
  a6=(a6-a3);
  a7=(a7*a6);
  a2=(a2+a7);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a4=(a5*a4);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][14] : 0;
  a4=arg[3]? arg[3][30] : 0;
  a4=(a4-a1);
  a2=(a2*a4);
  a1=arg[3]? arg[3][15] : 0;
  a6=arg[3]? arg[3][31] : 0;
  a6=(a6-a3);
  a1=(a1*a6);
  a2=(a2+a1);
  a4=casadi_sq(a4);
  a6=casadi_sq(a6);
  a4=(a4+a6);
  a5=(a5*a4);
  a2=(a2+a5);
  a0=(a0+a2);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int LF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int LF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int LF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int LF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void LF_incref(void) {
}

CASADI_SYMBOL_EXPORT void LF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int LF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int LF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real LF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int LF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgtI:(i0[2],i1[2],i2[32],i3[2])->(o0[5x2]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=1.;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  a2=arg[1]? arg[1][0] : 0;
  a3=arg[3]? arg[3][0] : 0;
  a2=(a2-a3);
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a0=arg[3]? arg[3][1] : 0;
  a1=(a1-a0);
  if (res[0]!=0) res[0][9]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgtI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgtI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgtI_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgtI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgtI_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GgtI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgtI_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtI_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtI_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gI:(i0[2],i1[2],i2[32],i3[2])->(o0[2]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[3]? arg[3][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gI_incref(void) {
}

CASADI_SYMBOL_EXPORT void gI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gI_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gI_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gI_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gI_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Ggt:(i0[2],i1[2],i2[32],i3[2])->(o0[5x0]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ggt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ggt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ggt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ggt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ggt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ggt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ggt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ggt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ggt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Ggt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Ggt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ggt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ggt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ggt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ggt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ggt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g:(i0[2],i1[2],i2[32],i3[2])->(o0[0]) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgtF:(i0[2],i1[2],i2[32],i3[2])->(o0[3x0]) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgtF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgtF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgtF_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgtF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgtF_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GgtF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgtF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gF:(i0[2],i1[2],i2[32],i3[2])->(o0[0]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gF_incref(void) {
}

CASADI_SYMBOL_EXPORT void gF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gF_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgineqIt:(i0[2],i1[2],i2[32],i3[2])->(o0[5x2]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][9]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int GgineqIt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgineqIt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgineqIt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgineqIt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgineqIt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgineqIt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgineqIt_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgineqIt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgineqIt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GgineqIt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgineqIt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgineqIt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgineqIt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgineqIt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgineqIt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgineqIt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gineqI:(i0[2],i1[2],i2[32],i3[2])->(o0[2]) */
static int casadi_f21(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gineqI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f21(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gineqI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gineqI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineqI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gineqI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineqI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gineqI_incref(void) {
}

CASADI_SYMBOL_EXPORT void gineqI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gineqI_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gineqI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gineqI_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineqI_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineqI_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineqI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineqI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gineqI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Ggineqt:(i0[2],i1[2],i2[32],i3[2])->(o0[5x2]) */
static int casadi_f22(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][9]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ggineqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f22(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ggineqt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ggineqt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ggineqt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ggineqt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ggineqt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ggineqt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ggineqt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ggineqt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Ggineqt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Ggineqt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ggineqt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ggineqt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ggineqt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ggineqt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ggineqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gineq:(i0[2],i1[2],i2[32],i3[2])->(o0[2]) */
static int casadi_f23(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gineq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f23(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gineq_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gineq_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineq_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gineq_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineq_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gineq_incref(void) {
}

CASADI_SYMBOL_EXPORT void gineq_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gineq_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gineq_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gineq_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineq_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineq_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineq_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineq_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gineq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgineqFt:(i0[2],i1[32],i2[2])->(o0[3x0]) */
static int casadi_f24(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgineqFt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f24(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgineqFt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgineqFt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgineqFt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgineqFt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgineqFt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgineqFt_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgineqFt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgineqFt_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int GgineqFt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgineqFt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgineqFt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgineqFt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgineqFt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgineqFt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgineqFt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gineqF:(i0[2],i1[32],i2[2])->(o0[0]) */
static int casadi_f25(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gineqF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f25(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gineqF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gineqF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineqF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gineqF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineqF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gineqF_incref(void) {
}

CASADI_SYMBOL_EXPORT void gineqF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gineqF_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int gineqF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gineqF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineqF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineqF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineqF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineqF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gineqF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
